image: registry.gitlab.com/pages/hugo/hugo_extended

pages:
  before_script:
    - apk add --no-cache go curl bash nodejs npm
  script:
#    - curl -fsSL https://deb.nodesource.com/setup_19.x | bash -
    - npm ci
    - hugo --config config.toml --minify --baseURL="https://next.lumao.eu/"
  artifacts:
    paths:
      - public
  only:
    - master
