language: go
go:
  - 1.11
install: go get github.com/spf13/hugo
before_script:
  - sudo apt-get update
  - sudo apt-get install nodejs npm
  - sudo npm set strict-ssl false
  - sudo npm install -g gulp
script:
  - go get -u github.com/tdewolff/minify/v2
  - npm install
  - gulp
  - hugo
  - gulp
  - bash ./deploy.sh
notifications:
    email:
        on_failure: always
branches:
  only:
  - master
