language: go
go:
  - 1.11
install: go get github.com/spf13/hugo
before_script:
  - sudo apt-get update
  - sudo apt-get install nodejs npm
  - sudo npm set strict-ssl false
  - sudo npm install -g gulp
script:
  - go get github.com/tdewolff/minify/cmd/minify
  - npm install
  - gulp
  - hugo
  - gulp
  - minify --recursive --verbose --match=\.*ml public/
  - bash ./deploy.sh
notifications:
    email:
        on_failure: always
branches:
  only:
  - master
