languageCode = "fr-fr"
title = "Développement Magento"
description = "Vous cherchez un expert Magento disponible qui connait vos problématiques ? C'est ici."
baseurl = "https://lumao.eu/"
theme = "lumao"
disableKinds = ["taxonomy","taxonomyTerm"]
paginate = 1000

[markup]
    [markup.goldmark]
        [markup.goldmark.renderer]
            unsafe = true
[params]
    hreflangEn = "en-us"
    hrefurlEn = "https://en.lumao.eu/"
    hreflangCh = "fr-ch"
    hrefurlCh = "https://lumao.ch/"
    hreflangFr = "fr-fr"
    hrefurlFr = "https://lumao.eu/"
    hreflangBe = "fr-be"
    hrefurlBe = "https://be.lumao.eu/"
    hreflangLu = "fr-lu"
    hrefurlLu = "https://lu.lumao.eu/"
    robots = "INDEX,FOLLOW"
    cities = "Annecy, Bordeaux, Chambéry, Grenoble, Lyon, Paris et dans toute la Haute-Savoie"
    city = "Annecy, France"
    postalCode = "74600"
    street = "22 bd du Semnoz"
    phone = "+33 (0)4 58 10 14 18"