languageCode = "fr-fr"
title = "Développement Magento"
description = "Vous cherchez un expert Magento disponible qui connait vos problématiques ? C'est ici."
baseurl = "https://lumao.eu/"
theme = "lumao"

[params]
    hreflang = "en"
    hrefurl = "https://en.lumao.eu/"
    robots = "INDEX,FOLLOW"