version: "2"
services:
  gulp:
    image: gabrielaraujof/nodejs-gulp-bower
    environment:
      - WORKDIR=/home/workspace
    volumes:
      - ./:/home/workspace
  jekyll:
    image: jekyll/jekyll
    volumes:
      - ./public:/srv/jekyll