name: Deploy staging
on:
  push:
    branches:
      - feat/next
jobs:
  deploy:
    runs-on: ubuntu-20.04
    steps:
      - name: Git checkout
        uses: actions/checkout@v4
        with:
          ref: "feat/next"

      - name: Setup hugo
        uses: peaceiris/actions-hugo@v2
        with:
          hugo-version: "0.83.1"
          extended: true

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: '15'

      - name: Build FR
        run: |
         npm ci
         hugo --config config.toml --minify -b https://next.lumao.eu/
         cp .gitignore public
         echo "next.lumao.eu" > public/CNAME

      - name: Pushes to another repository FR
        uses: cpina/github-action-push-to-another-repository@main
        env:
          API_TOKEN_GITHUB: ${{ secrets.TOKEN }}
        with:
          source-directory: 'public'
          destination-github-username: 'LavoWeb'
          destination-repository-name: 'LumaoNext'
          user-email: aurelien@lumao.eu
          target-branch: master
